# Configuration file for Calamares
# Syntax is YAML
---
modules-search: [ local ]

instances:
  - id:       clean_live
    module:   shellprocess
    config:   shellprocess_clean_live.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader
    - shellprocess@clean_live
    - umount
  - show:
    - finished

branding: default
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
