# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
keyName:                    us
xorgModel:                  pc105
xorgLayout:                 us
xorgVariant:                ""
xorgOptions:                ""
writeToConsole:             true
