title    Arch-Builder Live OS (@@ARCH@@, UEFI)
sort-key 01
architecture x64
linux    /boot/@@KERNEL_FILE@@
initrd   /boot/@@INITRAMFS_FILE@@
options  archisobasedir=arch archisosearchuuid=@@ARCHISO_UUID@@
