title    @@BOOT_TITLE@@ (@@ARCH@@, UEFI)
sort-key 01
linux    /@@INSTALL_DIR@@/boot/@@ARCH@@/@@KERNEL_FILE@@
initrd   /@@INSTALL_DIR@@/boot/@@ARCH@@/@@INITRAMFS_FILE@@
options  archisobasedir=@@INSTALL_DIR@@ archisosearchuuid=@@ARCHISO_UUID@@ @@BOOT_CMDLINE@@
